"""
Global News Sources Database — 20 Countries, 200+ Sources
Each country has: country_code, country_name, flag_emoji, primary_language,
crawl_schedule, local_priority, city_tier_1[5], city_tier_2[5], sources[10]
"""

GLOBAL_SOURCES = [
    # ━━━━━━━━━━━━━━━━━━━ 1. UNITED STATES ━━━━━━━━━━━━━━━━━━━
    {
        "country_code": "US",
        "country_name": "United States",
        "flag_emoji": "\U0001F1FA\U0001F1F8",
        "primary_language": "English",
        "crawl_schedule": "every_2_hours",
        "local_priority": 1,
        "city_tier_1": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix"],
        "city_tier_2": ["Austin", "Nashville", "Denver", "Portland", "Charlotte"],
        "sources": [
            {"name": "AP News", "url": "https://apnews.com", "rss_url": "https://rsshub.app/apnews/topics/apf-topnews", "feed_type": "rss", "category_tags": ["world", "science", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "NPR", "url": "https://npr.org", "rss_url": "https://feeds.npr.org/1001/rss.xml", "feed_type": "rss", "category_tags": ["world", "science", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "CNN", "url": "https://cnn.com", "rss_url": "http://rss.cnn.com/rss/cnn_topstories.rss", "feed_type": "rss", "category_tags": ["world", "money", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "NY Times", "url": "https://nytimes.com", "rss_url": "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml", "feed_type": "rss", "category_tags": ["world", "science", "money", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Washington Post", "url": "https://washingtonpost.com", "rss_url": "https://feeds.washingtonpost.com/rss/world", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "USA Today", "url": "https://usatoday.com", "rss_url": "http://rssfeeds.usatoday.com/usatoday-NewsTopStories", "feed_type": "rss", "category_tags": ["world", "entertainment", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "CBS News", "url": "https://cbsnews.com", "rss_url": "https://www.cbsnews.com/latest/rss/main", "feed_type": "rss", "category_tags": ["world", "money", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "ABC News", "url": "https://abcnews.go.com", "rss_url": "https://abcnews.go.com/abcnews/topstories", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "PBS NewsHour", "url": "https://pbs.org/newshour", "rss_url": "https://www.pbs.org/newshour/feeds/rss/headlines", "feed_type": "rss", "category_tags": ["world", "science", "history"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Reuters US", "url": "https://reuters.com", "rss_url": "https://www.reutersagency.com/feed/", "feed_type": "rss", "category_tags": ["world", "money", "science"], "language": "English", "logo_url": "", "status": "active"},
        ],
    },
    # ━━━━━━━━━━━━━━━━━━━ 2. UNITED KINGDOM ━━━━━━━━━━━━━━━━━━━
    {
        "country_code": "GB",
        "country_name": "United Kingdom",
        "flag_emoji": "\U0001F1EC\U0001F1E7",
        "primary_language": "English",
        "crawl_schedule": "every_2_hours",
        "local_priority": 1,
        "city_tier_1": ["London", "Manchester", "Birmingham", "Edinburgh", "Glasgow"],
        "city_tier_2": ["Bristol", "Liverpool", "Leeds", "Cardiff", "Belfast"],
        "sources": [
            {"name": "BBC News", "url": "https://bbc.co.uk/news", "rss_url": "https://feeds.bbci.co.uk/news/rss.xml", "feed_type": "rss", "category_tags": ["world", "science", "money", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "The Guardian", "url": "https://theguardian.com", "rss_url": "https://www.theguardian.com/world/rss", "feed_type": "rss", "category_tags": ["world", "science", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Sky News", "url": "https://news.sky.com", "rss_url": "https://news.sky.com/feeds/rss/home.xml", "feed_type": "rss", "category_tags": ["world", "money", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "The Independent", "url": "https://independent.co.uk", "rss_url": "https://www.independent.co.uk/news/rss", "feed_type": "rss", "category_tags": ["world", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "The Telegraph", "url": "https://telegraph.co.uk", "rss_url": "https://www.telegraph.co.uk/rss.xml", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Daily Mail", "url": "https://dailymail.co.uk", "rss_url": "https://www.dailymail.co.uk/news/index.rss", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "ITV News", "url": "https://itv.com/news", "rss_url": "https://www.itv.com/news/rss", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Metro UK", "url": "https://metro.co.uk", "rss_url": "https://metro.co.uk/feed/", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Evening Standard", "url": "https://standard.co.uk", "rss_url": "https://www.standard.co.uk/rss", "feed_type": "rss", "category_tags": ["local", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Reuters UK", "url": "https://uk.reuters.com", "rss_url": "https://www.reutersagency.com/feed/", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
        ],
    },
    # ━━━━━━━━━━━━━━━━━━━ 3. INDIA ━━━━━━━━━━━━━━━━━━━
    {
        "country_code": "IN",
        "country_name": "India",
        "flag_emoji": "\U0001F1EE\U0001F1F3",
        "primary_language": "English",
        "crawl_schedule": "every_2_hours",
        "local_priority": 1,
        "city_tier_1": ["Mumbai", "Delhi", "Bangalore", "Chennai", "Kolkata"],
        "city_tier_2": ["Hyderabad", "Pune", "Ahmedabad", "Jaipur", "Lucknow"],
        "sources": [
            {"name": "Times of India", "url": "https://timesofindia.indiatimes.com", "rss_url": "https://timesofindia.indiatimes.com/rssfeedstopstories.cms", "feed_type": "rss", "category_tags": ["world", "money", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "NDTV", "url": "https://ndtv.com", "rss_url": "https://feeds.feedburner.com/ndtvnews-top-stories", "feed_type": "rss", "category_tags": ["world", "science", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "The Hindu", "url": "https://thehindu.com", "rss_url": "https://www.thehindu.com/news/feeder/default.rss", "feed_type": "rss", "category_tags": ["world", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Hindustan Times", "url": "https://hindustantimes.com", "rss_url": "https://www.hindustantimes.com/feeds/rss/latest/rssfeed.xml", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Indian Express", "url": "https://indianexpress.com", "rss_url": "https://indianexpress.com/section/india/feed/", "feed_type": "rss", "category_tags": ["world", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Mint", "url": "https://livemint.com", "rss_url": "https://www.livemint.com/rss/news", "feed_type": "rss", "category_tags": ["money", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "India Today", "url": "https://indiatoday.in", "rss_url": "https://www.indiatoday.in/rss/home", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "News18", "url": "https://news18.com", "rss_url": "https://www.news18.com/rss/india.xml", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Economic Times", "url": "https://economictimes.indiatimes.com", "rss_url": "https://economictimes.indiatimes.com/rssfeedstopstories.cms", "feed_type": "rss", "category_tags": ["money", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Deccan Herald", "url": "https://deccanherald.com", "rss_url": "https://www.deccanherald.com/rss", "feed_type": "rss", "category_tags": ["world", "local"], "language": "English", "logo_url": "", "status": "active"},
        ],
    },
    # ━━━━━━━━━━━━━━━━━━━ 4. CANADA ━━━━━━━━━━━━━━━━━━━
    {
        "country_code": "CA",
        "country_name": "Canada",
        "flag_emoji": "\U0001F1E8\U0001F1E6",
        "primary_language": "English",
        "crawl_schedule": "every_2_hours",
        "local_priority": 2,
        "city_tier_1": ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa"],
        "city_tier_2": ["Edmonton", "Winnipeg", "Halifax", "Quebec City", "Victoria"],
        "sources": [
            {"name": "CBC News", "url": "https://cbc.ca/news", "rss_url": "https://rss.cbc.ca/lineup/topstories.xml", "feed_type": "rss", "category_tags": ["world", "science", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Globe and Mail", "url": "https://theglobeandmail.com", "rss_url": "https://www.theglobeandmail.com/arc/outboundfeeds/rss/category/canada/", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "CTV News", "url": "https://ctvnews.ca", "rss_url": "https://www.ctvnews.ca/rss/ctvnews-ca-top-stories-public-rss-1.822009", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "National Post", "url": "https://nationalpost.com", "rss_url": "https://nationalpost.com/feed", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Toronto Star", "url": "https://thestar.com", "rss_url": "https://www.thestar.com/search/?f=rss&t=article&c=news*", "feed_type": "rss", "category_tags": ["local", "world"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Global News", "url": "https://globalnews.ca", "rss_url": "https://globalnews.ca/feed/", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Montreal Gazette", "url": "https://montrealgazette.com", "rss_url": "https://montrealgazette.com/feed", "feed_type": "rss", "category_tags": ["local", "world"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Vancouver Sun", "url": "https://vancouversun.com", "rss_url": "https://vancouversun.com/feed", "feed_type": "rss", "category_tags": ["local", "world"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Ottawa Citizen", "url": "https://ottawacitizen.com", "rss_url": "https://ottawacitizen.com/feed", "feed_type": "rss", "category_tags": ["local", "world"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Macleans", "url": "https://macleans.ca", "rss_url": "https://macleans.ca/feed/", "feed_type": "rss", "category_tags": ["world", "science"], "language": "English", "logo_url": "", "status": "active"},
        ],
    },
    # ━━━━━━━━━━━━━━━━━━━ 5. AUSTRALIA ━━━━━━━━━━━━━━━━━━━
    {
        "country_code": "AU",
        "country_name": "Australia",
        "flag_emoji": "\U0001F1E6\U0001F1FA",
        "primary_language": "English",
        "crawl_schedule": "every_2_hours",
        "local_priority": 2,
        "city_tier_1": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
        "city_tier_2": ["Gold Coast", "Canberra", "Hobart", "Darwin", "Newcastle"],
        "sources": [
            {"name": "ABC Australia", "url": "https://abc.net.au/news", "rss_url": "https://www.abc.net.au/news/feed/2942460/rss.xml", "feed_type": "rss", "category_tags": ["world", "science", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Sydney Morning Herald", "url": "https://smh.com.au", "rss_url": "https://www.smh.com.au/rss/feed.xml", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "The Age", "url": "https://theage.com.au", "rss_url": "https://www.theage.com.au/rss/feed.xml", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "News.com.au", "url": "https://news.com.au", "rss_url": "https://www.news.com.au/content-feeds/latest-news-national/", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "SBS News", "url": "https://sbs.com.au/news", "rss_url": "https://www.sbs.com.au/news/feed", "feed_type": "rss", "category_tags": ["world", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "The Australian", "url": "https://theaustralian.com.au", "rss_url": "https://www.theaustralian.com.au/feed", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Brisbane Times", "url": "https://brisbanetimes.com.au", "rss_url": "https://www.brisbanetimes.com.au/rss/feed.xml", "feed_type": "rss", "category_tags": ["local", "world"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "9News Australia", "url": "https://9news.com.au", "rss_url": "https://www.9news.com.au/rss", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Guardian Australia", "url": "https://theguardian.com/au", "rss_url": "https://www.theguardian.com/au/rss", "feed_type": "rss", "category_tags": ["world", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Sky News Australia", "url": "https://skynews.com.au", "rss_url": "https://www.skynews.com.au/feed", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
        ],
    },
    # ━━━━━━━━━━━━━━━━━━━ 6. PAKISTAN ━━━━━━━━━━━━━━━━━━━
    {
        "country_code": "PK",
        "country_name": "Pakistan",
        "flag_emoji": "\U0001F1F5\U0001F1F0",
        "primary_language": "Urdu",
        "crawl_schedule": "every_4_hours",
        "local_priority": 2,
        "city_tier_1": ["Karachi", "Lahore", "Islamabad", "Rawalpindi", "Faisalabad"],
        "city_tier_2": ["Peshawar", "Quetta", "Multan", "Sialkot", "Hyderabad"],
        "sources": [
            {"name": "Dawn", "url": "https://dawn.com", "rss_url": "https://www.dawn.com/feeds/home", "feed_type": "rss", "category_tags": ["world", "money", "local"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Geo News", "url": "https://geo.tv", "rss_url": "https://www.geo.tv/rss/1/0", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "The News International", "url": "https://thenews.com.pk", "rss_url": "https://www.thenews.com.pk/rss/1/1", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Express Tribune", "url": "https://tribune.com.pk", "rss_url": "https://tribune.com.pk/feed/home", "feed_type": "rss", "category_tags": ["world", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "ARY News", "url": "https://arynews.tv", "rss_url": "https://arynews.tv/feed/", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Dunya News", "url": "https://dunyanews.tv", "rss_url": "https://dunyanews.tv/en/rss", "feed_type": "rss", "category_tags": ["world", "local"], "language": "Urdu", "logo_url": "", "status": "active"},
            {"name": "Pakistan Today", "url": "https://pakistantoday.com.pk", "rss_url": "https://www.pakistantoday.com.pk/feed/", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Daily Times PK", "url": "https://dailytimes.com.pk", "rss_url": "https://dailytimes.com.pk/feed/", "feed_type": "rss", "category_tags": ["world", "local"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "The Nation PK", "url": "https://nation.com.pk", "rss_url": "https://www.nation.com.pk/rss/headlines", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Samaa TV", "url": "https://samaa.tv", "rss_url": "https://www.samaa.tv/feed/", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "Urdu", "logo_url": "", "status": "active"},
        ],
    },
    # ━━━━━━━━━━━━━━━━━━━ 7. BANGLADESH ━━━━━━━━━━━━━━━━━━━
    {
        "country_code": "BD",
        "country_name": "Bangladesh",
        "flag_emoji": "\U0001F1E7\U0001F1E9",
        "primary_language": "Bangla",
        "crawl_schedule": "every_4_hours",
        "local_priority": 2,
        "city_tier_1": ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet"],
        "city_tier_2": ["Comilla", "Gazipur", "Rangpur", "Mymensingh", "Barisal"],
        "sources": [
            {"name": "The Daily Star BD", "url": "https://thedailystar.net", "rss_url": "https://www.thedailystar.net/frontpage/rss.xml", "feed_type": "rss", "category_tags": ["world", "money", "local"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Dhaka Tribune", "url": "https://dhakatribune.com", "rss_url": "https://www.dhakatribune.com/feed", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Prothom Alo", "url": "https://en.prothomalo.com", "rss_url": "https://en.prothomalo.com/feed", "feed_type": "rss", "category_tags": ["world", "local"], "language": "Bangla", "logo_url": "", "status": "active"},
            {"name": "bdnews24", "url": "https://bdnews24.com", "rss_url": "https://bdnews24.com/feed/", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Business Standard BD", "url": "https://tbsnews.net", "rss_url": "https://www.tbsnews.net/feed", "feed_type": "rss", "category_tags": ["money", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "The Independent BD", "url": "https://theindependentbd.com", "rss_url": "https://www.theindependentbd.com/feed", "feed_type": "rss", "category_tags": ["world", "local"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Financial Express BD", "url": "https://thefinancialexpress.com.bd", "rss_url": "https://thefinancialexpress.com.bd/feed", "feed_type": "rss", "category_tags": ["money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Daily Sun BD", "url": "https://daily-sun.com", "rss_url": "https://www.daily-sun.com/feed", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Bangla Tribune", "url": "https://banglatribune.com", "rss_url": "https://www.banglatribune.com/feed", "feed_type": "rss", "category_tags": ["world", "local"], "language": "Bangla", "logo_url": "", "status": "active"},
            {"name": "New Age BD", "url": "https://newagebd.net", "rss_url": "https://www.newagebd.net/rss.xml", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
        ],
    },
    # ━━━━━━━━━━━━━━━━━━━ 8. NIGERIA ━━━━━━━━━━━━━━━━━━━
    {
        "country_code": "NG",
        "country_name": "Nigeria",
        "flag_emoji": "\U0001F1F3\U0001F1EC",
        "primary_language": "English",
        "crawl_schedule": "every_4_hours",
        "local_priority": 2,
        "city_tier_1": ["Lagos", "Abuja", "Kano", "Ibadan", "Port Harcourt"],
        "city_tier_2": ["Benin City", "Kaduna", "Enugu", "Calabar", "Jos"],
        "sources": [
            {"name": "Punch Nigeria", "url": "https://punchng.com", "rss_url": "https://punchng.com/feed/", "feed_type": "rss", "category_tags": ["world", "money", "local"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Vanguard Nigeria", "url": "https://vanguardngr.com", "rss_url": "https://www.vanguardngr.com/feed/", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Premium Times", "url": "https://premiumtimesng.com", "rss_url": "https://www.premiumtimesng.com/feed", "feed_type": "rss", "category_tags": ["world", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "The Guardian NG", "url": "https://guardian.ng", "rss_url": "https://guardian.ng/feed/", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Daily Trust", "url": "https://dailytrust.com", "rss_url": "https://dailytrust.com/feed/", "feed_type": "rss", "category_tags": ["world", "local"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Channels TV", "url": "https://channelstv.com", "rss_url": "https://www.channelstv.com/feed/", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Sahara Reporters", "url": "https://saharareporters.com", "rss_url": "https://saharareporters.com/feed", "feed_type": "rss", "category_tags": ["world", "local"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "BusinessDay NG", "url": "https://businessday.ng", "rss_url": "https://businessday.ng/feed/", "feed_type": "rss", "category_tags": ["money", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "ThisDay", "url": "https://thisdaylive.com", "rss_url": "https://www.thisdaylive.com/feed/", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "The Nation NG", "url": "https://thenationonlineng.net", "rss_url": "https://thenationonlineng.net/feed/", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
        ],
    },
    # ━━━━━━━━━━━━━━━━━━━ 9. SOUTH AFRICA ━━━━━━━━━━━━━━━━━━━
    {
        "country_code": "ZA",
        "country_name": "South Africa",
        "flag_emoji": "\U0001F1FF\U0001F1E6",
        "primary_language": "English",
        "crawl_schedule": "every_4_hours",
        "local_priority": 2,
        "city_tier_1": ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth"],
        "city_tier_2": ["Bloemfontein", "East London", "Pietermaritzburg", "Stellenbosch", "Polokwane"],
        "sources": [
            {"name": "News24", "url": "https://news24.com", "rss_url": "https://feeds.news24.com/articles/news24/TopStories/rss", "feed_type": "rss", "category_tags": ["world", "money", "local"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "TimesLive", "url": "https://timeslive.co.za", "rss_url": "https://www.timeslive.co.za/rss/", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "IOL", "url": "https://iol.co.za", "rss_url": "https://www.iol.co.za/cmlink/1.640", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "EWN", "url": "https://ewn.co.za", "rss_url": "https://ewn.co.za/RSS%20Feeds/Latest%20News", "feed_type": "rss", "category_tags": ["world", "local"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Daily Maverick", "url": "https://dailymaverick.co.za", "rss_url": "https://www.dailymaverick.co.za/article/feed/", "feed_type": "rss", "category_tags": ["world", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Mail & Guardian", "url": "https://mg.co.za", "rss_url": "https://mg.co.za/feed/", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "The Citizen ZA", "url": "https://citizen.co.za", "rss_url": "https://www.citizen.co.za/feed/", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "SABC News", "url": "https://sabcnews.com", "rss_url": "https://www.sabcnews.com/sabcnews/feed/", "feed_type": "rss", "category_tags": ["world", "local"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "BusinessLive ZA", "url": "https://businesslive.co.za", "rss_url": "https://www.businesslive.co.za/rss/", "feed_type": "rss", "category_tags": ["money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "GroundUp", "url": "https://groundup.org.za", "rss_url": "https://www.groundup.org.za/feeds/articles/", "feed_type": "rss", "category_tags": ["world", "local"], "language": "English", "logo_url": "", "status": "active"},
        ],
    },
    # ━━━━━━━━━━━━━━━━━━━ 10. GERMANY ━━━━━━━━━━━━━━━━━━━
    {
        "country_code": "DE",
        "country_name": "Germany",
        "flag_emoji": "\U0001F1E9\U0001F1EA",
        "primary_language": "German",
        "crawl_schedule": "every_4_hours",
        "local_priority": 2,
        "city_tier_1": ["Berlin", "Munich", "Hamburg", "Frankfurt", "Cologne"],
        "city_tier_2": ["Stuttgart", "Dusseldorf", "Leipzig", "Dresden", "Hanover"],
        "sources": [
            {"name": "DW News", "url": "https://dw.com", "rss_url": "https://rss.dw.com/rdf/rss-en-top", "feed_type": "rss", "category_tags": ["world", "science", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Spiegel International", "url": "https://spiegel.de/international", "rss_url": "https://www.spiegel.de/international/index.rss", "feed_type": "rss", "category_tags": ["world", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Tagesschau", "url": "https://tagesschau.de", "rss_url": "https://www.tagesschau.de/xml/rss2", "feed_type": "rss", "category_tags": ["world", "money"], "language": "German", "logo_url": "", "status": "active"},
            {"name": "Sueddeutsche Zeitung", "url": "https://sueddeutsche.de", "rss_url": "https://rss.sueddeutsche.de/rss/Topthemen", "feed_type": "rss", "category_tags": ["world", "science"], "language": "German", "logo_url": "", "status": "active"},
            {"name": "FAZ", "url": "https://faz.net", "rss_url": "https://www.faz.net/rss/aktuell/", "feed_type": "rss", "category_tags": ["world", "money"], "language": "German", "logo_url": "", "status": "active"},
            {"name": "Die Zeit", "url": "https://zeit.de", "rss_url": "https://newsfeed.zeit.de/index", "feed_type": "rss", "category_tags": ["world", "science"], "language": "German", "logo_url": "", "status": "active"},
            {"name": "Handelsblatt", "url": "https://handelsblatt.com", "rss_url": "https://www.handelsblatt.com/contentexport/feed/top", "feed_type": "rss", "category_tags": ["money"], "language": "German", "logo_url": "", "status": "active"},
            {"name": "Stern", "url": "https://stern.de", "rss_url": "https://www.stern.de/feed/standard/all/", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "German", "logo_url": "", "status": "active"},
            {"name": "Die Welt", "url": "https://welt.de", "rss_url": "https://www.welt.de/feeds/latest.rss", "feed_type": "rss", "category_tags": ["world", "money"], "language": "German", "logo_url": "", "status": "active"},
            {"name": "The Local DE", "url": "https://thelocal.de", "rss_url": "https://www.thelocal.de/feeds/rss.php", "feed_type": "rss", "category_tags": ["local", "world"], "language": "English", "logo_url": "", "status": "active"},
        ],
    },
    # ━━━━━━━━━━━━━━━━━━━ 11. FRANCE ━━━━━━━━━━━━━━━━━━━
    {
        "country_code": "FR",
        "country_name": "France",
        "flag_emoji": "\U0001F1EB\U0001F1F7",
        "primary_language": "French",
        "crawl_schedule": "every_4_hours",
        "local_priority": 2,
        "city_tier_1": ["Paris", "Marseille", "Lyon", "Toulouse", "Nice"],
        "city_tier_2": ["Nantes", "Strasbourg", "Montpellier", "Bordeaux", "Lille"],
        "sources": [
            {"name": "France 24", "url": "https://france24.com/en", "rss_url": "https://www.france24.com/en/rss", "feed_type": "rss", "category_tags": ["world", "science", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "RFI", "url": "https://rfi.fr/en", "rss_url": "https://www.rfi.fr/en/rss", "feed_type": "rss", "category_tags": ["world", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Le Monde", "url": "https://lemonde.fr", "rss_url": "https://www.lemonde.fr/rss/une.xml", "feed_type": "rss", "category_tags": ["world", "science", "money"], "language": "French", "logo_url": "", "status": "active"},
            {"name": "Le Figaro", "url": "https://lefigaro.fr", "rss_url": "https://www.lefigaro.fr/rss/figaro_actualites.xml", "feed_type": "rss", "category_tags": ["world", "money"], "language": "French", "logo_url": "", "status": "active"},
            {"name": "Liberation", "url": "https://liberation.fr", "rss_url": "https://www.liberation.fr/arc/outboundfeeds/rss-all/collection/accueil-une/", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "French", "logo_url": "", "status": "active"},
            {"name": "Les Echos", "url": "https://lesechos.fr", "rss_url": "https://www.lesechos.fr/rss/rss_une.xml", "feed_type": "rss", "category_tags": ["money"], "language": "French", "logo_url": "", "status": "active"},
            {"name": "BFM TV", "url": "https://bfmtv.com", "rss_url": "https://www.bfmtv.com/rss/news-24-7/", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "French", "logo_url": "", "status": "active"},
            {"name": "L'Express", "url": "https://lexpress.fr", "rss_url": "https://www.lexpress.fr/arc/outboundfeeds/rss/alaune.xml", "feed_type": "rss", "category_tags": ["world", "science"], "language": "French", "logo_url": "", "status": "active"},
            {"name": "Le Point", "url": "https://lepoint.fr", "rss_url": "https://www.lepoint.fr/rss.xml", "feed_type": "rss", "category_tags": ["world", "money"], "language": "French", "logo_url": "", "status": "active"},
            {"name": "The Local FR", "url": "https://thelocal.fr", "rss_url": "https://www.thelocal.fr/feeds/rss.php", "feed_type": "rss", "category_tags": ["local", "world"], "language": "English", "logo_url": "", "status": "active"},
        ],
    },
    # ━━━━━━━━━━━━━━━━━━━ 12. JAPAN ━━━━━━━━━━━━━━━━━━━
    {
        "country_code": "JP",
        "country_name": "Japan",
        "flag_emoji": "\U0001F1EF\U0001F1F5",
        "primary_language": "Japanese",
        "crawl_schedule": "every_4_hours",
        "local_priority": 2,
        "city_tier_1": ["Tokyo", "Osaka", "Yokohama", "Nagoya", "Sapporo"],
        "city_tier_2": ["Fukuoka", "Kobe", "Kyoto", "Sendai", "Hiroshima"],
        "sources": [
            {"name": "Japan Times", "url": "https://japantimes.co.jp", "rss_url": "https://www.japantimes.co.jp/feed/", "feed_type": "rss", "category_tags": ["world", "science", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "NHK World", "url": "https://www3.nhk.or.jp/nhkworld", "rss_url": "https://www3.nhk.or.jp/rss/news/cat0.xml", "feed_type": "rss", "category_tags": ["world", "science"], "language": "Japanese", "logo_url": "", "status": "active"},
            {"name": "Nikkei Asia", "url": "https://asia.nikkei.com", "rss_url": "https://asia.nikkei.com/rss", "feed_type": "rss", "category_tags": ["money", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Mainichi", "url": "https://mainichi.jp/english", "rss_url": "https://mainichi.jp/rss/etc/mainichi-flash.rss", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "Japanese", "logo_url": "", "status": "active"},
            {"name": "Asahi Shimbun", "url": "https://asahi.com/ajw", "rss_url": "https://www.asahi.com/ajw/rss/index.rdf", "feed_type": "rss", "category_tags": ["world", "science"], "language": "Japanese", "logo_url": "", "status": "active"},
            {"name": "Kyodo News", "url": "https://english.kyodonews.net", "rss_url": "https://english.kyodonews.net/rss/news.xml", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Japan Today", "url": "https://japantoday.com", "rss_url": "https://japantoday.com/feed", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Nippon.com", "url": "https://nippon.com/en", "rss_url": "https://www.nippon.com/en/rss/headlines.rss", "feed_type": "rss", "category_tags": ["world", "history"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "The Diplomat", "url": "https://thediplomat.com", "rss_url": "https://thediplomat.com/feed/", "feed_type": "rss", "category_tags": ["world", "history"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Tokyo Reporter", "url": "https://tokyoreporter.com", "rss_url": "https://www.tokyoreporter.com/feed/", "feed_type": "rss", "category_tags": ["local", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
        ],
    },
    # ━━━━━━━━━━━━━━━━━━━ 13. BRAZIL ━━━━━━━━━━━━━━━━━━━
    {
        "country_code": "BR",
        "country_name": "Brazil",
        "flag_emoji": "\U0001F1E7\U0001F1F7",
        "primary_language": "Portuguese",
        "crawl_schedule": "every_4_hours",
        "local_priority": 2,
        "city_tier_1": ["Sao Paulo", "Rio de Janeiro", "Brasilia", "Salvador", "Belo Horizonte"],
        "city_tier_2": ["Curitiba", "Recife", "Fortaleza", "Porto Alegre", "Manaus"],
        "sources": [
            {"name": "Folha de S.Paulo", "url": "https://folha.uol.com.br", "rss_url": "https://feeds.folha.uol.com.br/emcimadahora/rss091.xml", "feed_type": "rss", "category_tags": ["world", "money", "entertainment"], "language": "Portuguese", "logo_url": "", "status": "active"},
            {"name": "Globo", "url": "https://g1.globo.com", "rss_url": "https://g1.globo.com/rss/g1/", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "Portuguese", "logo_url": "", "status": "active"},
            {"name": "Estadao", "url": "https://estadao.com.br", "rss_url": "https://www.estadao.com.br/arc/outboundfeeds/rss/", "feed_type": "rss", "category_tags": ["world", "money"], "language": "Portuguese", "logo_url": "", "status": "active"},
            {"name": "UOL", "url": "https://uol.com.br", "rss_url": "https://rss.uol.com.br/feed/noticias.xml", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "Portuguese", "logo_url": "", "status": "active"},
            {"name": "BBC Brasil", "url": "https://bbc.com/portuguese", "rss_url": "https://www.bbc.com/portuguese/topics/cez0n29ggrdt/rss.xml", "feed_type": "rss", "category_tags": ["world", "science"], "language": "Portuguese", "logo_url": "", "status": "active"},
            {"name": "Reuters Brasil", "url": "https://reuters.com/pt", "rss_url": "https://www.reutersagency.com/feed/", "feed_type": "rss", "category_tags": ["world", "money"], "language": "Portuguese", "logo_url": "", "status": "active"},
            {"name": "Valor Economico", "url": "https://valor.globo.com", "rss_url": "https://valor.globo.com/rss/", "feed_type": "rss", "category_tags": ["money"], "language": "Portuguese", "logo_url": "", "status": "active"},
            {"name": "Veja", "url": "https://veja.abril.com.br", "rss_url": "https://veja.abril.com.br/feed/", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "Portuguese", "logo_url": "", "status": "active"},
            {"name": "CartaCapital", "url": "https://cartacapital.com.br", "rss_url": "https://www.cartacapital.com.br/feed/", "feed_type": "rss", "category_tags": ["world", "science"], "language": "Portuguese", "logo_url": "", "status": "active"},
            {"name": "InfoMoney", "url": "https://infomoney.com.br", "rss_url": "https://www.infomoney.com.br/feed/", "feed_type": "rss", "category_tags": ["money"], "language": "Portuguese", "logo_url": "", "status": "active"},
        ],
    },
    # ━━━━━━━━━━━━━━━━━━━ 14. MEXICO ━━━━━━━━━━━━━━━━━━━
    {
        "country_code": "MX",
        "country_name": "Mexico",
        "flag_emoji": "\U0001F1F2\U0001F1FD",
        "primary_language": "Spanish",
        "crawl_schedule": "every_4_hours",
        "local_priority": 2,
        "city_tier_1": ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana"],
        "city_tier_2": ["Leon", "Merida", "Cancun", "Queretaro", "Oaxaca"],
        "sources": [
            {"name": "El Universal", "url": "https://eluniversal.com.mx", "rss_url": "https://www.eluniversal.com.mx/rss.xml", "feed_type": "rss", "category_tags": ["world", "money", "entertainment"], "language": "Spanish", "logo_url": "", "status": "active"},
            {"name": "Milenio", "url": "https://milenio.com", "rss_url": "https://www.milenio.com/rss", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "Spanish", "logo_url": "", "status": "active"},
            {"name": "Animal Politico", "url": "https://animalpolitico.com", "rss_url": "https://www.animalpolitico.com/feed/", "feed_type": "rss", "category_tags": ["world", "science"], "language": "Spanish", "logo_url": "", "status": "active"},
            {"name": "Proceso", "url": "https://proceso.com.mx", "rss_url": "https://www.proceso.com.mx/feed/", "feed_type": "rss", "category_tags": ["world", "history"], "language": "Spanish", "logo_url": "", "status": "active"},
            {"name": "La Jornada", "url": "https://jornada.com.mx", "rss_url": "https://www.jornada.com.mx/rss/portada.xml", "feed_type": "rss", "category_tags": ["world", "local"], "language": "Spanish", "logo_url": "", "status": "active"},
            {"name": "Excelsior", "url": "https://excelsior.com.mx", "rss_url": "https://www.excelsior.com.mx/rss.xml", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "Spanish", "logo_url": "", "status": "active"},
            {"name": "Sin Embargo", "url": "https://sinembargo.mx", "rss_url": "https://www.sinembargo.mx/feed/", "feed_type": "rss", "category_tags": ["world", "science"], "language": "Spanish", "logo_url": "", "status": "active"},
            {"name": "Aristegui Noticias", "url": "https://aristeguinoticias.com", "rss_url": "https://aristeguinoticias.com/feed/", "feed_type": "rss", "category_tags": ["world", "money"], "language": "Spanish", "logo_url": "", "status": "active"},
            {"name": "El Financiero", "url": "https://elfinanciero.com.mx", "rss_url": "https://www.elfinanciero.com.mx/arc/outboundfeeds/rss/", "feed_type": "rss", "category_tags": ["money"], "language": "Spanish", "logo_url": "", "status": "active"},
            {"name": "Mexico News Daily", "url": "https://mexiconewsdaily.com", "rss_url": "https://mexiconewsdaily.com/feed/", "feed_type": "rss", "category_tags": ["world", "local"], "language": "English", "logo_url": "", "status": "active"},
        ],
    },
    # ━━━━━━━━━━━━━━━━━━━ 15. KENYA ━━━━━━━━━━━━━━━━━━━
    {
        "country_code": "KE",
        "country_name": "Kenya",
        "flag_emoji": "\U0001F1F0\U0001F1EA",
        "primary_language": "English",
        "crawl_schedule": "daily",
        "local_priority": 3,
        "city_tier_1": ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret"],
        "city_tier_2": ["Thika", "Malindi", "Nyeri", "Machakos", "Naivasha"],
        "sources": [
            {"name": "Daily Nation", "url": "https://nation.africa", "rss_url": "https://nation.africa/feed", "feed_type": "rss", "category_tags": ["world", "money", "local"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "The Standard KE", "url": "https://standardmedia.co.ke", "rss_url": "https://www.standardmedia.co.ke/rss/headlines.php", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Business Daily KE", "url": "https://businessdailyafrica.com", "rss_url": "https://www.businessdailyafrica.com/rss", "feed_type": "rss", "category_tags": ["money", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "The Star Kenya", "url": "https://the-star.co.ke", "rss_url": "https://www.the-star.co.ke/rss", "feed_type": "rss", "category_tags": ["world", "local"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Capital FM KE", "url": "https://capitalfm.co.ke", "rss_url": "https://www.capitalfm.co.ke/news/feed/", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Citizen Digital", "url": "https://citizen.digital", "rss_url": "https://www.citizen.digital/feed", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Tuko", "url": "https://tuko.co.ke", "rss_url": "https://www.tuko.co.ke/feed", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "The East African", "url": "https://theeastafrican.co.ke", "rss_url": "https://www.theeastafrican.co.ke/feed", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Kenyans.co.ke", "url": "https://kenyans.co.ke", "rss_url": "https://www.kenyans.co.ke/rss.xml", "feed_type": "rss", "category_tags": ["local", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "K24 TV", "url": "https://k24tv.co.ke", "rss_url": "https://www.k24tv.co.ke/feed/", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
        ],
    },
    # ━━━━━━━━━━━━━━━━━━━ 16. EGYPT ━━━━━━━━━━━━━━━━━━━
    {
        "country_code": "EG",
        "country_name": "Egypt",
        "flag_emoji": "\U0001F1EA\U0001F1EC",
        "primary_language": "Arabic",
        "crawl_schedule": "daily",
        "local_priority": 3,
        "city_tier_1": ["Cairo", "Alexandria", "Giza", "Sharm El Sheikh", "Luxor"],
        "city_tier_2": ["Aswan", "Hurghada", "Port Said", "Suez", "Mansoura"],
        "sources": [
            {"name": "Ahram Online", "url": "https://english.ahram.org.eg", "rss_url": "https://english.ahram.org.eg/RSS.aspx", "feed_type": "rss", "category_tags": ["world", "money", "history"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Egypt Independent", "url": "https://egyptindependent.com", "rss_url": "https://egyptindependent.com/feed/", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Daily News Egypt", "url": "https://dailynewsegypt.com", "rss_url": "https://dailynewsegypt.com/feed/", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Egypt Today", "url": "https://egypttoday.com", "rss_url": "https://www.egypttoday.com/RSS", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Mada Masr", "url": "https://madamasr.com/en", "rss_url": "https://www.madamasr.com/en/feed/", "feed_type": "rss", "category_tags": ["world", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Al-Monitor Egypt", "url": "https://al-monitor.com/egypt", "rss_url": "https://www.al-monitor.com/rss", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Enterprise Egypt", "url": "https://enterprise.press", "rss_url": "https://enterprise.press/feed/", "feed_type": "rss", "category_tags": ["money", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Cairo Scene", "url": "https://cairoscene.com", "rss_url": "https://cairoscene.com/feed", "feed_type": "rss", "category_tags": ["entertainment", "local"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Al Ahram Weekly", "url": "https://weekly.ahram.org.eg", "rss_url": "https://weekly.ahram.org.eg/RSS.aspx", "feed_type": "rss", "category_tags": ["world", "history"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Egyptian Streets", "url": "https://egyptianstreets.com", "rss_url": "https://egyptianstreets.com/feed/", "feed_type": "rss", "category_tags": ["local", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
        ],
    },
    # ━━━━━━━━━━━━━━━━━━━ 17. UAE ━━━━━━━━━━━━━━━━━━━
    {
        "country_code": "AE",
        "country_name": "United Arab Emirates",
        "flag_emoji": "\U0001F1E6\U0001F1EA",
        "primary_language": "Arabic",
        "crawl_schedule": "every_4_hours",
        "local_priority": 2,
        "city_tier_1": ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Ras Al Khaimah"],
        "city_tier_2": ["Fujairah", "Umm Al Quwain", "Al Ain", "Khor Fakkan", "Dibba"],
        "sources": [
            {"name": "Gulf News", "url": "https://gulfnews.com", "rss_url": "https://gulfnews.com/rss", "feed_type": "rss", "category_tags": ["world", "money", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Khaleej Times", "url": "https://khaleejtimes.com", "rss_url": "https://www.khaleejtimes.com/rss", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "The National UAE", "url": "https://thenationalnews.com", "rss_url": "https://www.thenationalnews.com/rss", "feed_type": "rss", "category_tags": ["world", "science", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Arabian Business", "url": "https://arabianbusiness.com", "rss_url": "https://www.arabianbusiness.com/rss", "feed_type": "rss", "category_tags": ["money", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Al Arabiya English", "url": "https://english.alarabiya.net", "rss_url": "https://english.alarabiya.net/tools/rss", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Gulf Today", "url": "https://gulftoday.ae", "rss_url": "https://www.gulftoday.ae/rss", "feed_type": "rss", "category_tags": ["world", "local"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "WAM", "url": "https://wam.ae/en", "rss_url": "https://www.wam.ae/en/rss/all", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Zawya", "url": "https://zawya.com", "rss_url": "https://www.zawya.com/rss.xml", "feed_type": "rss", "category_tags": ["money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Emirates 247", "url": "https://emirates247.com", "rss_url": "https://www.emirates247.com/rss", "feed_type": "rss", "category_tags": ["local", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Lovin Dubai", "url": "https://lovindubai.com", "rss_url": "https://lovindubai.com/feed", "feed_type": "rss", "category_tags": ["local", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
        ],
    },
    # ━━━━━━━━━━━━━━━━━━━ 18. INDONESIA ━━━━━━━━━━━━━━━━━━━
    {
        "country_code": "ID",
        "country_name": "Indonesia",
        "flag_emoji": "\U0001F1EE\U0001F1E9",
        "primary_language": "Indonesian",
        "crawl_schedule": "every_4_hours",
        "local_priority": 2,
        "city_tier_1": ["Jakarta", "Surabaya", "Bandung", "Medan", "Semarang"],
        "city_tier_2": ["Makassar", "Palembang", "Denpasar", "Yogyakarta", "Malang"],
        "sources": [
            {"name": "Jakarta Post", "url": "https://thejakartapost.com", "rss_url": "https://www.thejakartapost.com/feed", "feed_type": "rss", "category_tags": ["world", "money", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Kompas", "url": "https://kompas.com", "rss_url": "https://rss.kompas.com/kompas.xml", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "Indonesian", "logo_url": "", "status": "active"},
            {"name": "Tempo", "url": "https://en.tempo.co", "rss_url": "https://en.tempo.co/rss/", "feed_type": "rss", "category_tags": ["world", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Detik", "url": "https://detik.com", "rss_url": "https://rss.detik.com/index.php/detikcom", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "Indonesian", "logo_url": "", "status": "active"},
            {"name": "CNN Indonesia", "url": "https://cnnindonesia.com", "rss_url": "https://www.cnnindonesia.com/rss", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "Indonesian", "logo_url": "", "status": "active"},
            {"name": "ANTARA", "url": "https://en.antaranews.com", "rss_url": "https://en.antaranews.com/rss/news.xml", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Jakarta Globe", "url": "https://jakartaglobe.id", "rss_url": "https://jakartaglobe.id/feed", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Coconuts Jakarta", "url": "https://coconuts.co/jakarta", "rss_url": "https://coconuts.co/jakarta/feed/", "feed_type": "rss", "category_tags": ["local", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Liputan6", "url": "https://liputan6.com", "rss_url": "https://www.liputan6.com/rss", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "Indonesian", "logo_url": "", "status": "active"},
            {"name": "Tirto", "url": "https://tirto.id", "rss_url": "https://tirto.id/feed/", "feed_type": "rss", "category_tags": ["world", "science"], "language": "Indonesian", "logo_url": "", "status": "active"},
        ],
    },
    # ━━━━━━━━━━━━━━━━━━━ 19. PHILIPPINES ━━━━━━━━━━━━━━━━━━━
    {
        "country_code": "PH",
        "country_name": "Philippines",
        "flag_emoji": "\U0001F1F5\U0001F1ED",
        "primary_language": "English",
        "crawl_schedule": "every_4_hours",
        "local_priority": 2,
        "city_tier_1": ["Manila", "Quezon City", "Cebu City", "Davao City", "Makati"],
        "city_tier_2": ["Taguig", "Pasig", "Zamboanga", "Cagayan de Oro", "Iloilo City"],
        "sources": [
            {"name": "Philippine Daily Inquirer", "url": "https://inquirer.net", "rss_url": "https://www.inquirer.net/fullfeed", "feed_type": "rss", "category_tags": ["world", "money", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Philippine Star", "url": "https://philstar.com", "rss_url": "https://www.philstar.com/rss/headlines", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Rappler", "url": "https://rappler.com", "rss_url": "https://www.rappler.com/feed/", "feed_type": "rss", "category_tags": ["world", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "ABS-CBN News", "url": "https://news.abs-cbn.com", "rss_url": "https://news.abs-cbn.com/feed", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "GMA News", "url": "https://gmanetwork.com/news", "rss_url": "https://data.gmanetwork.com/gno/rss/news/feed.xml", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Manila Bulletin", "url": "https://mb.com.ph", "rss_url": "https://mb.com.ph/feed/", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Manila Times", "url": "https://manilatimes.net", "rss_url": "https://www.manilatimes.net/feed/", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "CNN Philippines", "url": "https://cnnphilippines.com", "rss_url": "https://www.cnnphilippines.com/cnn-rss-feeds", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "BusinessWorld PH", "url": "https://bworldonline.com", "rss_url": "https://www.bworldonline.com/feed/", "feed_type": "rss", "category_tags": ["money", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Sunstar", "url": "https://sunstar.com.ph", "rss_url": "https://www.sunstar.com.ph/feeds", "feed_type": "rss", "category_tags": ["local", "world"], "language": "English", "logo_url": "", "status": "active"},
        ],
    },
    # ━━━━━━━━━━━━━━━━━━━ 20. SOUTH KOREA ━━━━━━━━━━━━━━━━━━━
    {
        "country_code": "KR",
        "country_name": "South Korea",
        "flag_emoji": "\U0001F1F0\U0001F1F7",
        "primary_language": "Korean",
        "crawl_schedule": "every_4_hours",
        "local_priority": 2,
        "city_tier_1": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon"],
        "city_tier_2": ["Gwangju", "Ulsan", "Suwon", "Jeju City", "Changwon"],
        "sources": [
            {"name": "Korea Herald", "url": "https://koreaherald.com", "rss_url": "http://www.koreaherald.com/common/rss_xml.php?ct=102", "feed_type": "rss", "category_tags": ["world", "money", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Korea Times", "url": "https://koreatimes.co.kr", "rss_url": "https://www.koreatimes.co.kr/www/rss/rss.xml", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Yonhap News", "url": "https://en.yna.co.kr", "rss_url": "https://en.yna.co.kr/RSS/news.xml", "feed_type": "rss", "category_tags": ["world", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "KBS World", "url": "https://world.kbs.co.kr", "rss_url": "https://world.kbs.co.kr/rss/rss_news.htm?lang=e", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Arirang", "url": "https://arirang.com", "rss_url": "https://www.arirang.com/rss/rss.asp", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "JoongAng Daily", "url": "https://koreajoongangdaily.joins.com", "rss_url": "https://koreajoongangdaily.joins.com/xmlfile/rss_joins.xml", "feed_type": "rss", "category_tags": ["world", "money"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Chosun Ilbo English", "url": "https://english.chosun.com", "rss_url": "https://english.chosun.com/site/data/rss/rss.xml", "feed_type": "rss", "category_tags": ["world", "entertainment"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Hankyoreh", "url": "https://english.hani.co.kr", "rss_url": "https://english.hani.co.kr/rss/", "feed_type": "rss", "category_tags": ["world", "science"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Dong-A Ilbo", "url": "https://english.donga.com", "rss_url": "https://english.donga.com/rss/", "feed_type": "rss", "category_tags": ["world", "history"], "language": "English", "logo_url": "", "status": "active"},
            {"name": "Maeil Business", "url": "https://pulsenews.co.kr", "rss_url": "https://pulsenews.co.kr/rss.xml", "feed_type": "rss", "category_tags": ["money"], "language": "English", "logo_url": "", "status": "active"},
        ],
    },
]


# Utility: Get country config by country code
def get_country_by_code(code: str) -> dict:
    for c in GLOBAL_SOURCES:
        if c["country_code"] == code:
            return c
    return None


# Utility: Get all active sources for a country
def get_active_sources(country_code: str) -> list:
    country = get_country_by_code(country_code)
    if not country:
        return []
    return [s for s in country["sources"] if s.get("status") == "active"]


# Utility: Get all country codes
def get_all_country_codes() -> list:
    return [c["country_code"] for c in GLOBAL_SOURCES]


# Utility: Get country list for frontend
def get_countries_list() -> list:
    return [
        {
            "country_code": c["country_code"],
            "country_name": c["country_name"],
            "flag_emoji": c["flag_emoji"],
            "primary_language": c["primary_language"],
        }
        for c in GLOBAL_SOURCES
    ]
